sonar.projectKey=mercadol-pithing
sonar.organization=mercadol-pithing
sonar.projectName=MercadoL Pithing
sonar.projectVersion=1.0.0

sonar.sources=apps,services,packages
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/coverage/**,**/*.test.ts,**/*.spec.ts,**/*.test.tsx,**/*.spec.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=**/*.test.ts,**/*.spec.ts,**/*.test.tsx,**/*.spec.tsx,**/node_modules/**,**/dist/**,**/build/**,**/.next/**

sonar.qualitygate.wait=true
