apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@mercadol-pithing.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mercadol-pithing-tls
  namespace: mercadol-pithing
spec:
  secretName: mercadol-pithing-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - mercadol-pithing.example.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mercadol-pithing-wildcard-tls
  namespace: mercadol-pithing
spec:
  secretName: mercadol-pithing-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "*.mercadol-pithing.example.com"
  - mercadol-pithing.example.com
