apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mercadol-pithing-network-policy
  namespace: mercadol-pithing
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: mercadol-pithing
    - podSelector:
        matchLabels:
          app: web
    - podSelector:
        matchLabels:
          app: api
    - podSelector:
        matchLabels:
          app: embeddings
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - to:
    - podSelector:
        matchLabels:
          app: minio
    ports:
    - protocol: TCP
      port: 9000
  - to: []
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
