apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mercadol-pithing-monitor
  namespace: mercadol-pithing
  labels:
    app: mercadol-pithing
spec:
  selector:
    matchLabels:
      app: api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mercadol-pithing-web-monitor
  namespace: mercadol-pithing
  labels:
    app: mercadol-pithing
spec:
  selector:
    matchLabels:
      app: web
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
